--#BAI TAP 1-------------
--#PHAN I----------------
--1--
--Tao Database--
CREATE DATABASE QLBH
--Table KHACHHANG--
CREATE TABLE KHACHHANG(
	MAKH char(4),
	HOTEN varchar(40),
	DCHI varchar(50),
	SODT varchar(20),
	NGSINH smalldatetime,
	NGDK smalldatetime,
	DOANHSO money,
	PRIMARY KEY (MAKH))
--Table NHANVIEN--
CREATE TABLE NHANVIEN(
	MANV char(4),
	HOTEN varchar(40),
	SODT varchar(20),
	NGVL smalldatetime,
	PRIMARY KEY (MANV))
--Table SANPHAM--
CREATE TABLE SANPHAM(
	MASP char(4),
	TENSP varchar(40),
	DVT varchar(20),
	NUOCSX varchar(40),
	GIA money,
	PRIMARY KEY (MASP))
--Table HOADON--
CREATE TABLE HOADON(
	SOHD int,
	NGHD smalldatetime,
	MAKH char(4),
	MANV char(4),
	TRIGIA money,
	PRIMARY KEY (SOHD))
--Table CTHD--
CREATE TABLE CTHD(
	SOHD int,
	MASP char(4),
	SL int,
	PRIMARY KEY (SOHD,MASP))
--Tao Foreign Key--
ALTER TABLE HOADON ADD
CONSTRAINT FK_HD_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
CONSTRAINT FK_HD_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
ALTER TABLE CTHD ADD
CONSTRAINT FK_CTHD_HD FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD),
CONSTRAINT FK_CTHD_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)

--2--
ALTER TABLE SANPHAM ADD GHICHU varchar(20)
--3--
ALTER TABLE KHACHHANG ADD LOAIKH tinyint
--4--
ALTER TABLE SANPHAM ALTER COLUMN GHICHU varchar(100)
--5--
ALTER TABLE SANPHAM DROP COLUMN GHICHU
--6--
ALTER TABLE KHACHHANG ADD
CONSTRAINT CK_KH_LOAIKH CHECK(LOAIKH IN ('Vang lai','Thuong xuyen','Vip'))
--7--
ALTER TABLE SANPHAM ADD
CONSTRAINT CK_SP_DVT CHECK(DVT IN ('cay','hop','cai','quyen','chuc'))
--8--
